name: run tests
on: 
  push:
    branches: "*"
  pull_request:
    branches:
      - master
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v2
        name: setup python
        with:
          python-version: 3.5

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 4

      - name: Run Tests
        run: |
          python setup.py install
          printf 'export NEX2_URI="postgresql://"\n' > test_variables.sh
          printf 'export ES_URI="http://localhost:9200/"\n' >> test_variables.sh
          printf 'export S3_BUCKET="S3 BUCKET"\n' >> test_variables.sh
          printf 'export S3_SECRET_KEY="S3 SECRET KEY"\n' >> test_variables.sh
          printf 'export S3_ACCESS_KEY="S3 ACCESS KEY"\n' >> test_variables.sh
          printf 'export BOTO_CONFIG=/dev/null\n' >> test_variables.sh
          printf 'export PREVIEW_URL="https://preview.yeastgenome.org/"\n' >> test_variables.sh
          make NOSEOPTS='--with-coverage' tests
